### ISSUE TITLE
Hodnota pole StavVZ

### ISSUE THREAD

**Issue by vrana** [HlidacStatu/verejne-zakazky#4]
[Dokumentace](https://hlidacstatu.github.io/verejne-zakazky/VerejneZakazkySchema/index.html) uvádí dvě pole pro stav veřejné zakázky: `StavVZ` a `StavZakazky`. Michal smaže `StavZakazky`.

Dále není jasné, co do `StavVZ` uložit. http://www.isvz.cz/ProfilyZadavatelu/Profil_Zadavatele_137_2006_SchemaVZ.zip má tento číselník:

```xml
<xs:enumeration value="VZ neukončena"><xs:annotation><xs:documentation xml:lang="cz">Veřejná zakázka neukončena</xs:documentation></xs:annotation></xs:enumeration>
<xs:enumeration value="VZ byla zadána"><xs:annotation><xs:documentation xml:lang="cz">Veřejná byla zadána</xs:documentation></xs:annotation></xs:enumeration>
<xs:enumeration value="VZ byla zrušena"><xs:annotation><xs:documentation xml:lang="cz">Veřejná zakázka byla zrušena</xs:documentation></xs:annotation></xs:enumeration>
<xs:enumeration value="Ukončeno plnění smlouvy na základě VZ"><xs:annotation><xs:documentation xml:lang="cz">Ukončeno plnění smlouvy na základě veřejné zakázky</xs:documentation></xs:annotation></xs:enumeration>
```

Zadavatelé to uvádí jako volný text, např. https://zakazky.krajbezkorupce.cz/profile_display_263.html/XMLdataVZ?od=01022018&do=01032018 má "ukončeno plnění smlouvy na základě veřejné zakázky", https://nen.nipez.cz/profil/MVCR/XMLdataVZ?od=12072017&do=12072017 má "zakázka neukončena".

Michal má tento číselník:

```c
public enum StavyZakazky
{
    [Devmasters.Core.NiceDisplayName("Oznámen úmysl vyhlásit tendr")] Umysl = 1,
    [Devmasters.Core.NiceDisplayName("Tendr zahájen")] Zahajeno = 100,
    [Devmasters.Core.NiceDisplayName("Tendr se vyhodnocuje")] Vyhodnocovani = 200,
    [Devmasters.Core.NiceDisplayName("Tendr byl ukončen")] Ukonceno = 300,
    [Devmasters.Core.NiceDisplayName("Nejasný stav")] Jine = 0,
}
```

Není jasné, jak tyto dva číselníky namapovat na sebe.

**Comment by michalblaha** [comment]
V transformovanem JSON tento stav neuvadej. Jeho urceni muze byt zavisle na dalsich zaznamech v DB, ke kterym transformacni skritp nema pristup v dobe transformace. Hodnotu nastavi Hlidac pri ukladani transformovaneho JSON.

Pokud se ukaze, ze toto reseni neni dobre, budeme hledat dalsi (vcetne prip. pristupu scriptu k dodatecnym datum)
