### ISSUE TITLE
Hodnota pole KonecnaHodnotaBezDPH

### ISSUE THREAD

**Issue by vrana** [HlidacStatu/verejne-zakazky#5]
Ve výsledné struktuře má být pole `KonecnaHodnotaBezDPH`. Ve zdrojovém XML jsem našel jen `zakazka/dodavatel/cena_celkem_dle_smlouvy_bez_DPH`. Popis pole `dodavatel` je „Struktura pro předání informací o vítězném uchazači (=dodavateli VZ)“, takže to vypadá, že by to mohlo být ono, nicméně pole `dodavatel` může být uvedeno víckrát:

```xml
<xs:element name="dodavatel" type="DodavatelStructure" minOccurs="0" maxOccurs="unbounded"/>
```

Co když skutečně bude uvedeno víckrát? Má být celková cena součet všech dodavatelů?

**Comment by michalblaha** [comment]
Pokud bude uvedena vicekrat, predpoklada se delena zakazka mezi vice dodavatelu, takze uvadejme soucet vsech cen.
