### ISSUE TITLE
Pole KonecnaHodnotaBezDPH

### ISSUE THREAD

**Issue by vrana** [HlidacStatu/verejne-zakazky#8]
Ve veřejných zakázkách jsou dvě různé hodnoty, které jde považovat za `KonecnaHodnotaBezDPH`. Příklad: https://zakazky.krajbezkorupce.cz/contract_display_13340.html

Jednak je to „Smluvní cena v Kč bez DPH“ u dodavatele, tato cena je i v XML jako `zakazka/dodavatel/cena_celkem_dle_smlouvy_bez_DPH`. A jednak je to „Skutečně uhrazená cena“, která v XML není. Zatím jsem nenašel zakázku, kde by se tyto dvě ceny lišily, ale co když se budou lišit? Co když jedna z nich bude chybět?

**Comment by michalblaha** [comment]
Berme primarne v uvahu `zakazka/dodavatel/cena_celkem_dle_smlouvy_bez_DPH`
pokud bude chybet, ale bude existovat "Skutečně uhrazená cena“, pouzijme tu. 

Pokud se budou lisi, rozdil ignorujme a berme cenu podle smlouvy

**Comment by vrana** [comment]
„Skutečně uhrazená cena“ prozatím ignoruji.
